################################################################################
# ==> Tasks for linux-wls Role for configure a Oracle Linux 7 system with
# ==> requirements for Fusion Middleware infrastructrure installation.
# ==> Supports version 12.2.1
# ==> author: Christos Vezalis
################################################################################
- name: Set facts
  set_fact:
    packages_list:
      - 'binutils'
      - 'compat-libcap1'
      - 'compat-libstdc++-33.x86_64'
      - 'gcc.x86_64'
      - 'gcc-c++.x86_64'
      - 'glibc.x86_64'
      - 'glibc-devel.x86_64'
      - 'libaio.x86_64'
      - 'libaio-devel.x86_64'
      - 'libgcc.x86_64'
      - 'libstdc++.x86_64'
      - 'libstdc++-devel.x86_64'
      - 'ksh'
      - 'make'
      - 'sysstat'
    kernel_params:
            kernel.shmmax: 2147483648
            kernel.shmall: 524288
            net.core.rmem_max: 16777216
            net.core.wmem_max: 16777216
            net.ipv4.tcp_rmem: 4096 87380 16777216
            net.ipv4.tcp_wmem: 4096 65536 16777216
            vm.swappiness: 10
            vm.dirty_background_ratio: 5
            vm.dirty_ratio: 10
            fs.file-max: 262144
            net.ipv4.tcp_keepalive_time: 300
            net.ipv4.tcp_keepalive_intvl: 60
            net.ipv4.tcp_keepalive_probes: 10
    soft_no_file: 4096
    hard_no_file: 65536
    soft_nproc: 2047
    hard_nproc: 16384
    
# ==> Configure Linux
- name: Install required libraries
  yum: name={{ item }} state=present
  with_items: {{ packages_list }}
- name: Disable SELinux
  selinux: state=disabled
- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: kernel_params

# ==> Create user and groups
- name: Create groups
  group: name={{ oracle_group }} state=present
- name: Create user
  user: name={{ oracle_user }} groups={{ oracle_group }} password={{ oracle_os_user_pass }}
  
# ==> Add open file and process limits for oracle user
- name: Create a shell profile with file and process limits for oracle user
  template: src=oracle-limits.sh dest=/etc/profile.d/

# ==> Add limits for oracle user
- name: Add oracle user limits
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} {{ item.limit }} {{ item.type}} {{ item.value }}'
  with_items:
    - { limit: 'soft', type: nofile, value: '{{ soft_no_file }}' }
    - { limit: 'hard', type: nofile, value: '{{ hard_no_file }}' }
    - { limit: 'soft', type: nproc, value: '{{ soft_nproc }}' }
    - { limit: 'hard', type: nproc, value: '{{ hard_nproc }}' }

# ==> Create Base Directories
- name: Create Oracle Home directory
  file: state=directory path={{ middleware_home }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Create Domain Home directory
  file: state=directory path={{ domains_home }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Create Applications Home directory
  file: state=directory path={{ applications_home }} owner={{ oracle_user }} group={{ oracle_group }}

